galaxy_info:
  author: Juri Calleri
  description: This role deploys NodeJS for Raspberry OS
  company: ---
  license: GPLv3
  min_ansible_version: 2.9
  platforms:
    - name: Raspberry OS 
  galaxy_tags:
    - nodejs

dependencies: []