---
- include_tasks: bluetooth-capabilities.yml
  loop: "{{ bluetooth_capabilities }}"
  when: bluetooth_capabilities is defined

- name: Create folders for bluetooth configuration
  file:
    path: "{{ room_assistant_config_path }}"
    state: directory
    mode: '0755'

- name: Setup bluetooth template
  template:
    src: bluetooth-room-detection.yml.j2
    dest: "{{ room_assistant_config_path }}/local.yml"
  notify: "enable restart room assistant"

- include_tasks: ending.yml